"""Deterministic Old Testament Citation Anchors in the New Testament (WP-026).

Implements Scripture-interpreting-Scripture cross-referencing by cataloging canonical
Old Testament quotations, prophetic fulfillments, and covenant anchors quoted by apostolic
writers (Paul, Peter, Hebrews, Gospels, Acts).

Every entry pairs:
- NT OSIS reference & apostolic introductory formula (e.g. 'καθὼς γέγραπται')
- OT OSIS reference & original Hebrew WLC text
- Septuagint (LXX) textual variation where relevant
- Covenant theme and deep theological exposition of how apostolic theology builds upon the OT bedrock.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any
from rich.markup import escape


class CitationType(str, Enum):
    """Classification of how an Old Testament passage is employed in the New Testament."""
    DIRECT_QUOTE = "DIRECT_QUOTE"                  # Verbatim or near-verbatim citation
    PROPHETIC_FULFILLMENT = "PROPHETIC_FULFILLMENT"  # Explicit fulfillment formula ("that it might be fulfilled")
    ALLUSION = "ALLUSION"                          # Clear verbal and conceptual dependency
    COVENANT_TYPOLOGY = "COVENANT_TYPOLOGY"        # Structural sanctuary/covenant/priesthood typology


@dataclass(frozen=True)
class OTCitation:
    """Deterministic representation of an OT quotation or major covenant anchor in the NT."""
    nt_osis: str                    # e.g. "Rom.1.17"
    ot_osis: str                    # e.g. "Hab.2.4"
    ot_book: str                    # e.g. "Habakkuk"
    ot_ref_display: str             # e.g. "Habakkuk 2:4"
    nt_ref_display: str             # e.g. "Romans 1:17"
    citation_type: CitationType
    introductory_formula: str       # e.g. "καθὼς γέγραπται (As it is written)"
    nt_text_snippet: str            # e.g. "The just shall live by faith."
    ot_text_kjv: str                # e.g. "The just shall live by his faith."
    ot_hebrew: str                  # Hebrew WLC text
    lxx_reading: str                # Septuagint Greek text (if pertinent)
    covenant_theme: str             # e.g. "Righteousness by Faith / Covenant Trust"
    theological_significance: str   # Deep exposition of apostolic theological grounding


# ---------------------------------------------------------------------------
# Canonical Dataset of Old Testament Citations in the New Testament
# ---------------------------------------------------------------------------

_CANONICAL_CITATIONS: list[OTCitation] = [
    # ── ROMANS ─────────────────────────────────────────────────────────────
    OTCitation(
        nt_osis="Rom.1.17",
        ot_osis="Hab.2.4",
        ot_book="Habakkuk",
        ot_ref_display="Habakkuk 2:4",
        nt_ref_display="Romans 1:17",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="The just shall live by faith.",
        ot_text_kjv="Behold, his soul which is lifted up is not upright in him: but the just shall live by his faith.",
        ot_hebrew="וְצַדִּיק בֶּאֱמוּנָתוֹ יִחְיֶה",
        lxx_reading="ὁ δὲ δίκαιος ἐκ πίστεώς μου ζήσεται",
        covenant_theme="Righteousness by Faith / Steadfast Trust",
        theological_significance=(
            "The structural spine of Paul's soteriology. In Habakkuk, God commanded unwavering trust in His covenant "
            "promise during national collapse under Babylon. Paul reveals that true life is never generated by human legal merit, "
            "but received through resting trust in God's revealed righteousness in Jesus Christ."
        ),
    ),
    OTCitation(
        nt_osis="Rom.2.24",
        ot_osis="Isa.52.5",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 52:5",
        nt_ref_display="Romans 2:24",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="For the name of God is blasphemed among the Gentiles through you, as it is written.",
        ot_text_kjv="Now therefore, what have I here, saith the LORD, that my people is taken away for nought?... and my name continually every day is blasphemed.",
        ot_hebrew="וְתָמִיד כָּל־הַיּוֹם שְׁמִי מִנֹּאָץ",
        lxx_reading="δι’ ὑμᾶς διὰ παντὸς τὸ ὄνομά μου βλασφημεῖται ἐν τοῖς ἔθνεσιν",
        covenant_theme="Covenant Hypocrisy & God's Holy Name",
        theological_significance=(
            "Paul shatters religious pride by demonstrating that possession of the Torah without internal heart circumcision "
            "dishonors God before the watching world, directly quoting Isaiah's lament over Israel's dishonoring of Yahweh."
        ),
    ),
    OTCitation(
        nt_osis="Rom.3.4",
        ot_osis="Ps.51.4",
        ot_book="Psalms",
        ot_ref_display="Psalm 51:4",
        nt_ref_display="Romans 3:4",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="That thou mightest be justified in thy sayings, and mightest overcome when thou art judged.",
        ot_text_kjv="Against thee, thee only, have I sinned... that thou mightest be justified when thou speakest, and be clear when thou judgest.",
        ot_hebrew="לְמַעַן תִּצְדַּק בְּדָבְרֶךָ תִּזְכֶּה בְשָׁפְטֶךָ",
        lxx_reading="ὅπως ἂν δικαιωθῇς ἐν τοῖς λόγοις σου καὶ νικήσῃς ἐν τῷ κρίνεσθαί σε",
        covenant_theme="The Divine Theodicy / God's Truthfulness",
        theological_significance=(
            "David's penitential confession after his great sin becomes Paul's demonstration that human unfaithfulness "
            "can never invalidate God's covenant faithfulness. When God's character is scrutinized in the cosmic judgment, "
            "His righteousness is vindicated beyond dispute."
        ),
    ),
    OTCitation(
        nt_osis="Rom.3.10",
        ot_osis="Ps.14.1",
        ot_book="Psalms",
        ot_ref_display="Psalm 14:1–3",
        nt_ref_display="Romans 3:10–12",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="There is none righteous, no, not one: There is none that understandeth, there is none that seeketh after God.",
        ot_text_kjv="The fool hath said in his heart, There is no God. They are corrupt, they have done abominable works, there is none that doeth good.",
        ot_hebrew="אֵין עֹשֵׂה־טוֹב אֵין גַּם־אֶחָד",
        lxx_reading="οὐκ ἔστιν ποιῶν χρηστότητα, οὐκ ἔστιν ἕως ἑνός",
        covenant_theme="Universal Human Depravity",
        theological_significance=(
            "The opening movement of Paul's catena (chain of OT citations) from Psalms and Ecclesiastes proving that all humanity—"
            "both Jew and Greek—stands under the indictment of sin, shutting every human mouth before God."
        ),
    ),
    OTCitation(
        nt_osis="Rom.3.13",
        ot_osis="Ps.5.9",
        ot_book="Psalms",
        ot_ref_display="Psalm 5:9 / Psalm 140:3",
        nt_ref_display="Romans 3:13",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="[Catena continuation]",
        nt_text_snippet="Their throat is an open sepulchre; with their tongues they have used deceit; the poison of asps is under their lips.",
        ot_text_kjv="Their throat is an open sepulchre; they flatter with their tongue. / They have sharpened their tongues like a serpent; adders' poison is under their lips.",
        ot_hebrew="קֶבֶר־פָּתוּחַ גְּרוֹנָם לְשׁוֹנָם יַחֲלִיקוּן / חֲמַת עַכְשׁוּב תַּחַת שְׂפָתֵימוֹ",
        lxx_reading="τάφος ἀνεῳγμένος ὁ λάρυγξ αὐτῶν... ἰὸς ἀσπίδων ὑπὸ τὰ χείλη αὐτῶν",
        covenant_theme="Anatomy of Sin: Speech & Corruption",
        theological_significance=(
            "Paul uses David's imagery of venomous deception to anatomize the total depravity of the human heart, "
            "showing that corruption inevitably poisons human communication and relationships."
        ),
    ),
    OTCitation(
        nt_osis="Rom.3.14",
        ot_osis="Ps.10.7",
        ot_book="Psalms",
        ot_ref_display="Psalm 10:7",
        nt_ref_display="Romans 3:14",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="[Catena continuation]",
        nt_text_snippet="Whose mouth is full of cursing and bitterness.",
        ot_text_kjv="His mouth is full of cursing and deceit and fraud: under his tongue is mischief and vanity.",
        ot_hebrew="אָלָה פִּיהוּ מָלֵא וּמִרְמוֹת וָתֹךְ",
        lxx_reading="οὗ ἀρᾶς τὸ στόμα αὐτοῦ γέμει καὶ πικρίας",
        covenant_theme="Anatomy of Sin: Malice",
        theological_significance="Further OT documentation of sinful rebellion expressed through bitter curses against God and neighbour.",
    ),
    OTCitation(
        nt_osis="Rom.3.15",
        ot_osis="Isa.59.7",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 59:7–8",
        nt_ref_display="Romans 3:15–17",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="[Catena continuation]",
        nt_text_snippet="Their feet are swift to shed blood: Destruction and misery are in their ways: And the way of peace have they not known.",
        ot_text_kjv="Their feet run to evil, and they make haste to shed innocent blood: their thoughts are thoughts of iniquity; wasting and destruction are in their paths.",
        ot_hebrew="רַגְלֵיהֶם לָרַע יָרֻצוּ וִימַהֲרוּ לִשְׁפֹּךְ דָּם נָקִי",
        lxx_reading="οἱ δὲ πόδες αὐτῶν ἐπὶ πονηρίαν τρέχουσι, ταχινοὶ ἐκχέαι αἷμα",
        covenant_theme="Anatomy of Sin: Violence & Ruin",
        theological_significance=(
            "From speech to action: Isaiah's prophetic confession of Israel's violent rebellion proves that human society "
            "alienated from God descends into destruction and loses the knowledge of covenant shalom."
        ),
    ),
    OTCitation(
        nt_osis="Rom.3.18",
        ot_osis="Ps.36.1",
        ot_book="Psalms",
        ot_ref_display="Psalm 36:1",
        nt_ref_display="Romans 3:18",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="[Catena climax]",
        nt_text_snippet="There is no fear of God before their eyes.",
        ot_text_kjv="The transgression of the wicked saith within my heart, that there is no fear of God before his eyes.",
        ot_hebrew="אֵין־פַּחַד אֱלֹהִים לְנֶגֶד עֵינָיו",
        lxx_reading="οὐκ ἔστιν φόβος θεοῦ ἀπέναντι τῶν ὀφθαλμῶν αὐτῶν",
        covenant_theme="The Root of All Sin: Absence of the Fear of God",
        theological_significance=(
            "The root diagnostic of the fallen human condition: sin is not merely bad behavior but the total absence of "
            "reverence, awe, and submission before the Holy Creator."
        ),
    ),
    OTCitation(
        nt_osis="Rom.3.20",
        ot_osis="Ps.143.2",
        ot_book="Psalms",
        ot_ref_display="Psalm 143:2",
        nt_ref_display="Romans 3:20",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="διότι (Because / Wherefore)",
        nt_text_snippet="Therefore by the deeds of the law there shall no flesh be justified in his sight.",
        ot_text_kjv="And enter not into judgment with thy servant: for in thy sight shall no man living be justified.",
        ot_hebrew="כִּי לֹא־יִצְדַּק לְפָנֶיךָ כָל־חָי",
        lxx_reading="ὅτι οὐ δικαιωθήσεται ἐνώπιόν σου πᾶς ζῶν",
        covenant_theme="Impossibility of Self-Justification",
        theological_significance=(
            "Paul anchors his central legal conclusion in David's plea. The Torah reveals sin; it was never designed "
            "to provide a mechanism for fallen man to present his own obedience as the legal ground of acceptance with God."
        ),
    ),
    OTCitation(
        nt_osis="Rom.4.3",
        ot_osis="Gen.15.6",
        ot_book="Genesis",
        ot_ref_display="Genesis 15:6",
        nt_ref_display="Romans 4:3",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="τί γὰρ ἡ γραφὴ λέγει; (For what saith the scripture?)",
        nt_text_snippet="Abraham believed God, and it was counted unto him for righteousness.",
        ot_text_kjv="And he believed in the LORD; and he counted it to him for righteousness.",
        ot_hebrew="וְהֶאֱמִן בַּיהוָה וַיַּחְשְׁבֶהָ לּוֹ צְדָקָה",
        lxx_reading="καὶ ἐπίστευσεν Ἀβρὰμ τῷ θεῷ, καὶ ἐλογίσθη αὐτῷ εἰς δικαιοσύνην",
        covenant_theme="Imputed Righteousness through Faith",
        theological_significance=(
            "The foundational covenant precedent: Abraham was justified by faith prior to circumcision, prior to Sinai, "
            "and without works of merit. Righteousness is credited (logizomai / chashav) as an unearned gift to whoever rests in God's promise."
        ),
    ),
    OTCitation(
        nt_osis="Rom.4.7",
        ot_osis="Ps.32.1",
        ot_book="Psalms",
        ot_ref_display="Psalm 32:1–2",
        nt_ref_display="Romans 4:7–8",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθάπερ καὶ Δαυὶδ λέγει (Even as David also describeth)",
        nt_text_snippet="Blessed are they whose iniquities are forgiven, and whose sins are covered. Blessed is the man to whom the Lord will not impute sin.",
        ot_text_kjv="Blessed is he whose transgression is forgiven, whose sin is covered. Blessed is the man unto whom the LORD imputeth not iniquity.",
        ot_hebrew="אַשְׁרֵי נְשׂוּי־פֶּשַׁע כְּסוּי חֲטָאָה אַשְׁרֵי אָדָם לֹא יַחְשֹׁב יְהוָה לוֹ עָוֹן",
        lxx_reading="μακάριοι ὧν ἀφέθησαν αἱ ἀνομίαι καὶ ὧν ἐπεκαλύφθησαν αἱ ἁμαρτίαι",
        covenant_theme="Non-Imputation of Iniquity / Forgiveness",
        theological_significance=(
            "David's second witness alongside Abraham: justification is not God overlooking sin, but God covering transgression "
            "and refusing to charge the debt to the penitent believer's ledger."
        ),
    ),
    OTCitation(
        nt_osis="Rom.4.17",
        ot_osis="Gen.17.5",
        ot_book="Genesis",
        ot_ref_display="Genesis 17:5",
        nt_ref_display="Romans 4:17",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="I have made thee a father of many nations.",
        ot_text_kjv="Neither shall thy name any more be called Abram, but thy name shall be Abraham; for a father of many nations have I made thee.",
        ot_hebrew="כִּי אַב־הֲמוֹן גּוֹיִם נְתַתִּיךָ",
        lxx_reading="ὅτι πατέρα πολλῶν ἐθνῶν τέθεικά σε",
        covenant_theme="The Universal Abrahamic Promise",
        theological_significance=(
            "Proves that God's covenant with Abraham always had the Gentiles in view. True sons of Abraham are defined "
            "not by ethnic genealogy but by shared faith in the God who gives life to the dead."
        ),
    ),
    OTCitation(
        nt_osis="Rom.4.18",
        ot_osis="Gen.15.5",
        ot_book="Genesis",
        ot_ref_display="Genesis 15:5",
        nt_ref_display="Romans 4:18",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="κατὰ τὸ εἰρημένον (According to that which was spoken)",
        nt_text_snippet="So shall thy seed be.",
        ot_text_kjv="And he brought him forth abroad, and said, Look now toward heaven, and tell the stars... And he said unto him, So shall thy seed be.",
        ot_hebrew="כֹּה יִהְיֶה זַרְעֶךָ",
        lxx_reading="οὕτως ἔσται τὸ σπέρμα σου",
        covenant_theme="Faith Against Hope / Miraculous Life",
        theological_significance=(
            "Abraham believed in hope against hope, trusting God to produce countless spiritual heirs from a body effectively dead."
        ),
    ),
    OTCitation(
        nt_osis="Rom.7.7",
        ot_osis="Exod.20.17",
        ot_book="Exodus",
        ot_ref_display="Exodus 20:17 / Deut 5:21",
        nt_ref_display="Romans 7:7",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ὁ νόμος ἔλεγεν (The law said)",
        nt_text_snippet="Thou shalt not covet.",
        ot_text_kjv="Thou shalt not covet thy neighbour's house, thou shalt not covet thy neighbour's wife...",
        ot_hebrew="לֹא תַחְמֹד בֵּית רֵעֶךָ",
        lxx_reading="οὐκ ἐπιθυμήσεις",
        covenant_theme="The Tenth Commandment / Inward Conviction",
        theological_significance=(
            "Paul points specifically to the Tenth Commandment to demonstrate the spiritual, inward character of God's law. "
            "Unlike human legal codes that govern only external acts, the Decalogue condemns internal desire (epithumia / chamad)."
        ),
    ),
    OTCitation(
        nt_osis="Rom.8.36",
        ot_osis="Ps.44.22",
        ot_book="Psalms",
        ot_ref_display="Psalm 44:22",
        nt_ref_display="Romans 8:36",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="For thy sake we are killed all the day long; we are accounted as sheep for the slaughter.",
        ot_text_kjv="Yea, for thy sake are we killed all the day long; we are counted as sheep for the slaughter.",
        ot_hebrew="כִּי־עָלֶיךָ הֹרַגְנוּ כָל־הַיּוֹם נֶחְשַׁבְנוּ כְּצֹאן טִבְחָה",
        lxx_reading="ὅτι ἕνεκα σοῦ θανατούμεθα ὅλην τὴν ἡμέραν, ἐλογίσθημεν ὡς πρόβατα σφαγῆς",
        covenant_theme="Suffering for God's Sake / Overcoming Love",
        theological_significance=(
            "Paul quotes the lament of Israel's righteous sufferers not to express despair, but to declare that in all "
            "these tribulations the believer is more than a conqueror through Christ's unshakeable love."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.7",
        ot_osis="Gen.21.12",
        ot_book="Genesis",
        ot_ref_display="Genesis 21:12",
        nt_ref_display="Romans 9:7",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἀλλ’ (But)",
        nt_text_snippet="In Isaac shall thy seed be called.",
        ot_text_kjv="In all that Sarah hath said unto thee, hearken unto her voice; for in Isaac shall thy seed be called.",
        ot_hebrew="כִּי בְיִצְחָק יִקָּרֵא לְךָ זָרַע",
        lxx_reading="ὅτι ἐν Ἰσαὰκ κληθήσεταί σοι σπέρμα",
        covenant_theme="Sovereign Election / Children of Promise",
        theological_significance=(
            "Establishes that biological descent from Abraham has never been the true ground of covenant election. "
            "God chose Isaac over Ishmael to show that covenant inheritance belongs to promise, not natural flesh."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.9",
        ot_osis="Gen.18.10",
        ot_book="Genesis",
        ot_ref_display="Genesis 18:10, 14",
        nt_ref_display="Romans 9:9",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἐπαγγελίας γὰρ ὁ λόγος οὗτος (For this is the word of promise)",
        nt_text_snippet="At this time will I come, and Sara shall have a son.",
        ot_text_kjv="I will certainly return unto thee according to the time of life; and, lo, Sarah thy wife shall have a son.",
        ot_hebrew="שׁוֹב אָשׁוּב אֵלֶיךָ כָּעֵת חַיָּה וְהִנֵּה־בֵן לְשָׂרָה אִשְׁתֶּךָ",
        lxx_reading="κατὰ τὸν καιρὸν τοῦτον ἐλεύσομαι καὶ ἔσται τῇ Σάρρᾳ υἱός",
        covenant_theme="The Word of Divine Promise",
        theological_significance="Underlines that divine redemption is created by supernatural divine initiative, impossible by human power alone.",
    ),
    OTCitation(
        nt_osis="Rom.9.12",
        ot_osis="Gen.25.23",
        ot_book="Genesis",
        ot_ref_display="Genesis 25:23",
        nt_ref_display="Romans 9:12",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἐῤῥήθη αὐτῇ ὅτι (It was said unto her)",
        nt_text_snippet="The elder shall serve the younger.",
        ot_text_kjv="Two nations are in thy womb, and two manner of people... and the elder shall serve the younger.",
        ot_hebrew="וְרַב יַעֲבֹד צָעִיר",
        lxx_reading="καὶ ὁ μείζων δουλεύσει τῷ ἐλάσσονι",
        covenant_theme="Election Before Works",
        theological_significance=(
            "Pronounced before the twins were born or had done good or evil, proving that God's purpose according to election "
            "stands not of works, but of Him that calleth."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.13",
        ot_osis="Mal.1.2",
        ot_book="Malachi",
        ot_ref_display="Malachi 1:2–3",
        nt_ref_display="Romans 9:13",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="Jacob have I loved, but Esau have I hated.",
        ot_text_kjv="I have loved you, saith the LORD. Yet ye say, Wherein hast thou loved us? Was not Esau Jacob's brother? saith the LORD: yet I loved Jacob, and I hated Esau...",
        ot_hebrew="וָאֹהַב אֶת־יַעֲקֹב וְאֶת־עֵשָׂו שָׂנֵאתִי",
        lxx_reading="τὸν Ἰακὼβ ἠγάπησα, τὸν δὲ Ἠσαῦ ἐμίσησα",
        covenant_theme="Covenant Favor vs Rejection of Birthright",
        theological_significance=(
            "In Malachi, God contrasts Jacob's covenant role with Edom's profane rejection of the sanctuary promise. "
            "Paul uses it to defend God's freedom to bestow His covenant grace sovereignly."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.15",
        ot_osis="Exod.33.19",
        ot_book="Exodus",
        ot_ref_display="Exodus 33:19",
        nt_ref_display="Romans 9:15",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="τῷ Μωϋσεῖ γὰρ λέγει (For he saith to Moses)",
        nt_text_snippet="I will have mercy on whom I will have mercy, and I will have compassion on whom I will have compassion.",
        ot_text_kjv="I will make all my goodness pass before thee... and will be gracious to whom I will be gracious, and will shew mercy on whom I will shew mercy.",
        ot_hebrew="וְחַנֹּתִי אֶת־אֲשֶׁר אָחֹן וְרִחַמְתִּי אֶת־אֲשֶׁר אֲרַחֵם",
        lxx_reading="ἐλεήσω ὃν ἂν ἐλεῶ καὶ οἰκτιρήσω ὃν ἂν οἰκτίρω",
        covenant_theme="Sovereignty of Divine Mercy",
        theological_significance=(
            "Given when Moses pled for Israel after the golden calf apostasy. God reveals that mercy is never a human debt, "
            "but pure divine grace freely bestowed by the sovereign Lord."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.17",
        ot_osis="Exod.9.16",
        ot_book="Exodus",
        ot_ref_display="Exodus 9:16",
        nt_ref_display="Romans 9:17",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="λέγει γὰρ ἡ γραφὴ τῷ Φαραὼ (For the scripture saith unto Pharaoh)",
        nt_text_snippet="Even for this same purpose have I raised thee up, that I might shew my power in thee, and that my name might be declared throughout all the earth.",
        ot_text_kjv="And in very deed for this cause have I raised thee up, for to shew in thee my power; and that my name may be declared throughout all the earth.",
        ot_hebrew="וְאוּלָם בַּעֲבוּר זֹאת הֶעֱמַדְתִּיךָ בַּעֲבוּר הַרְאֹתְךָ אֶת־כֹּחִי",
        lxx_reading="εἰς αὐτὸ τοῦτο ἐξήγειρά σε, ὅπως ἐνδείξωμαι ἐν σοὶ τὴν δύναμίν μου",
        covenant_theme="God Overruling Rebellion for Glory",
        theological_significance=(
            "Demonstrates that even stubborn human tyrants like Pharaoh cannot thwart God's redemptive plan; "
            "God overrules rebellion to manifest His holy power and proclaim His name to all nations."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.25",
        ot_osis="Hos.2.23",
        ot_book="Hosea",
        ot_ref_display="Hosea 2:23",
        nt_ref_display="Romans 9:25",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ὡς καὶ ἐν τῷ Ὡσηὲ λέγει (As he saith also in Osee)",
        nt_text_snippet="I will call them my people, which were not my people; and her beloved, which was not beloved.",
        ot_text_kjv="And I will sow her unto me in the earth; and I will have mercy upon her that had not obtained mercy; and I will say to them which were not my people, Thou art my people...",
        ot_hebrew="וְרִחַמְתִּי אֶת־לֹא רֻחָמָה וְאָמַרְתִּי לְלֹא־עַמִּי עַמִּי־אַתָּה",
        lxx_reading="καλέσω τὸν οὐ λαόν μου λαόν μου καὶ τὴν οὐκ ἠγαπημένην ἠγαπημένην",
        covenant_theme="Adoption of Outcasts / Ingathering of Gentiles",
        theological_significance=(
            "Hosea's prophecy of Israel's restoration after exile is applied typologically by Paul to the inclusion "
            "of the Gentiles: those completely outside the covenant are sovereignly brought into divine sonship."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.26",
        ot_osis="Hos.1.10",
        ot_book="Hosea",
        ot_ref_display="Hosea 1:10",
        nt_ref_display="Romans 9:26",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="[Hosea continuation]",
        nt_text_snippet="And it shall come to pass, that in the place where it was said unto them, Ye are not my people; there shall they be called the children of the living God.",
        ot_text_kjv="Yet the number of the children of Israel shall be as the sand of the sea... and it shall come to pass, that in the place where it was said unto them, Ye are not my people, there it shall be said unto them, Ye are the sons of the living God.",
        ot_hebrew="וְהָיָה בִּמְקוֹם אֲשֶׁר־יֵאָמֵר לָהֶם לֹא־עַמִּי אַתֶּם יֵאָמֵר לָהֶם בְּנֵי אֵל־חָי",
        lxx_reading="καὶ ἔσται ἐν τῷ τόπῳ οὗ ἐρρήθη αὐτοῖς, Οὐ λαός μου ὑμεῖς, ἐκεῖ κληθήσονται υἱοὶ θεοῦ ζῶντος",
        covenant_theme="Children of the Living God",
        theological_significance="Reverses the curse of Lo-ammi ('Not My People') into highest covenant dignity: sons of the living God.",
    ),
    OTCitation(
        nt_osis="Rom.9.27",
        ot_osis="Isa.10.22",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 10:22–23",
        nt_ref_display="Romans 9:27–28",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="Ἡσαΐας δὲ κράζει ὑπὲρ τοῦ Ἰσραήλ (Esaias also crieth concerning Israel)",
        nt_text_snippet="Though the number of the children of Israel be as the sand of the sea, a remnant shall be saved.",
        ot_text_kjv="For though thy people Israel be as the sand of the sea, yet a remnant of them shall return: the consumption decreed shall overflow with righteousness.",
        ot_hebrew="כִּי אִם־יִהְיֶה עַמְּךָ יִשְׂרָאֵל כְּחוֹל הַיָּם שְׁאָר יָשׁוּב בּוֹ",
        lxx_reading="ἐὰν ᾖ ὁ ἀριθμὸς τῶν υἱῶν Ἰσραὴλ ὡς ἡ ἄμμος τῆς θαλάσσης, τὸ ὑπόλειμμα σωθήσεται",
        covenant_theme="The Faithful Remnant Doctrine",
        theological_significance=(
            "Paul introduces the classic biblical Remnant doctrine: salvation is never a guaranteed ethnic wholesale heritage; "
            "amid apostasy, God preserves a faithful, believing remnant who cling to His covenant."
        ),
    ),
    OTCitation(
        nt_osis="Rom.9.33",
        ot_osis="Isa.28.16",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 28:16 / Isaiah 8:14",
        nt_ref_display="Romans 9:33",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="Behold, I lay in Sion a stumblingstone and rock of offence: and whosoever believeth on him shall not be ashamed.",
        ot_text_kjv="Behold, I lay in Zion for a foundation a stone, a tried stone, a precious corner stone... he that believeth shall not make haste. / And he shall be for a sanctuary; but for a stone of stumbling and for a rock of offence...",
        ot_hebrew="הִנְנִי יִסַּד בְּצִיּוֹן אָבֶן אֶבֶן בֹּחַן פִּנַּת יִקְרַת / וּלְאֶבֶן נֶגֶף וּלְצוּר מִכְשׁוֹל",
        lxx_reading="ἰδοὺ τίθημι ἐν Σιὼν λίθον προσκόμματος καὶ πέτραν σκανδάλου",
        covenant_theme="Christ the Cornerstone vs Stumbling Stone",
        theological_significance=(
            "Paul fuses Isaiah 8:14 (the Sanctuary Lord who becomes a stumbling stone to unbelief) and Isaiah 28:16 "
            "(the precious foundation stone). To self-reliant legalism, Christ crucified is an offensive stumbling block; "
            "to faith, He is eternal security."
        ),
    ),
    OTCitation(
        nt_osis="Rom.10.5",
        ot_osis="Lev.18.5",
        ot_book="Leviticus",
        ot_ref_display="Leviticus 18:5",
        nt_ref_display="Romans 10:5",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="Μωϋσῆς γὰρ γράφει (For Moses describeth)",
        nt_text_snippet="That the man which doeth those things shall live by them.",
        ot_text_kjv="Ye shall therefore keep my statutes, and my judgments: which if a man do, he shall live in them: I am the LORD.",
        ot_hebrew="אֲשֶׁר יַעֲשֶׂה אֹתָם הָאָדָם וָחַי בָּהֶם אֲנִי יְהוָה",
        lxx_reading="ὁ ποιήσας αὐτὰ ἄνθρωπος ζήσεται ἐν αὐτοῖς",
        covenant_theme="Righteousness of the Law vs Faith",
        theological_significance=(
            "Contrasts the principle of works (requiring flawless personal performance for life) with the righteousness "
            "of faith which receives life as a free gift in Christ."
        ),
    ),
    OTCitation(
        nt_osis="Rom.10.6",
        ot_osis="Deut.30.12",
        ot_book="Deuteronomy",
        ot_ref_display="Deuteronomy 30:12–14",
        nt_ref_display="Romans 10:6–8",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἡ δὲ ἐκ πίστεως δικαιοσύνη οὕτως λέγει (But the righteousness which is of faith speaketh on this wise)",
        nt_text_snippet="Say not in thine heart, Who shall ascend into heaven?... The word is nigh thee, even in thy mouth, and in thy heart: that is, the word of faith, which we preach.",
        ot_text_kjv="It is not in heaven, that thou shouldest say, Who shall go up for us to heaven, and bring it unto us?... But the word is very nigh unto thee, in thy mouth, and in thy heart...",
        ot_hebrew="לֹא בַשָּׁמַיִם הִוא... כִּי־קָרוֹב אֵלֶיךָ הַדָּבָר מְאֹד בְּפִיךָ וּבִלְבָבְךָ",
        lxx_reading="ἐγγύς σου τὸ ῥῆμά ἐστιν, ἐν τῷ στόματί σου καὶ ἐν τῇ καρδίᾳ σου",
        covenant_theme="Nearness of the Gospel Word",
        theological_significance=(
            "Paul applies Moses' covenant renewal sermon to Christ: we do not need to scale heaven or plumb the abyss; "
            "Christ has come down, died, and risen. The word of faith is immediately accessible to the heart and mouth."
        ),
    ),
    OTCitation(
        nt_osis="Rom.10.11",
        ot_osis="Isa.28.16",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 28:16",
        nt_ref_display="Romans 10:11",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="λέγει γὰρ ἡ γραφή (For the scripture saith)",
        nt_text_snippet="Whosoever believeth on him shall not be ashamed.",
        ot_text_kjv="He that believeth shall not make haste.",
        ot_hebrew="הַמַּאֲמִין לֹא יָחִישׁ",
        lxx_reading="πᾶς ὁ πιστεύων ἐπ’ αὐτῷ οὐ καταισχυνθήσεται",
        covenant_theme="Universal Promise to Faith",
        theological_significance="Emphasizes 'whosoever' (pas) from the Septuagint: no one who rests in Christ will ever be put to shame.",
    ),
    OTCitation(
        nt_osis="Rom.10.13",
        ot_osis="Joel.2.32",
        ot_book="Joel",
        ot_ref_display="Joel 2:32",
        nt_ref_display="Romans 10:13",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="[Causal Scripture Ground]",
        nt_text_snippet="For whosoever shall call upon the name of the Lord shall be saved.",
        ot_text_kjv="And it shall come to pass, that whosoever shall call on the name of the LORD shall be delivered.",
        ot_hebrew="כֹּל אֲשֶׁר־יִקְרָא בְּשֵׁם יְהוָה יִמָּלֵט",
        lxx_reading="πᾶς ὃς ἂν ἐπικαλέσηται τὸ ὄνομα Κυρίου σωθήσεται",
        covenant_theme="Calling Upon Yahweh / Jesus as Lord",
        theological_significance=(
            "Joel's eschatological prophecy of calling on the name of Yahweh for salvation is applied directly to the Lord Jesus Christ, "
            "identifying Jesus as Yahweh in the flesh."
        ),
    ),
    OTCitation(
        nt_osis="Rom.10.15",
        ot_osis="Isa.52.7",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 52:7 / Nahum 1:15",
        nt_ref_display="Romans 10:15",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="How beautiful are the feet of them that preach the gospel of peace, and bring glad tidings of good things!",
        ot_text_kjv="How beautiful upon the mountains are the feet of him that bringeth good tidings, that publisheth peace; that bringeth good tidings of good, that publisheth salvation...",
        ot_hebrew="מַה־נָּאווּ עַל־הֶהָרִים רַגְלֵי מְבַשֵׂר מַשְׁמִיעַ שָׁלוֹם",
        lxx_reading="ὡς ὡραῖοι οἱ πόδες τῶν εὐαγγελιζομένων εἰρήνην",
        covenant_theme="The Herald of Salvation",
        theological_significance="Celebrates the sent ambassadors of the gospel heralding the King's triumphant arrival and sovereign peace.",
    ),
    OTCitation(
        nt_osis="Rom.10.16",
        ot_osis="Isa.53.1",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 53:1",
        nt_ref_display="Romans 10:16",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="Ἡσαΐας γὰρ λέγει (For Esaias saith)",
        nt_text_snippet="Lord, who hath believed our report?",
        ot_text_kjv="Who hath believed our report? and to whom is the arm of the LORD revealed?",
        ot_hebrew="מִי הֶאֱמִין לִשְׁמֻעָתֵנוּ וּזְרוֹעַ יְהוָה עַל־מִי נִגְלָתָה",
        lxx_reading="Κύριε, τίς ἐπίστευσεν τῇ ἀκοῇ ἡμῶν;",
        covenant_theme="The Suffering Servant Rejected",
        theological_significance="Explains Israel's widespread rejection of the gospel: the prophets themselves foretold that few would believe the report of the Suffering Servant.",
    ),
    OTCitation(
        nt_osis="Rom.10.18",
        ot_osis="Ps.19.4",
        ot_book="Psalms",
        ot_ref_display="Psalm 19:4",
        nt_ref_display="Romans 10:18",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἀλλὰ λέγω (But I say)",
        nt_text_snippet="Their sound went into all the earth, and their words unto the ends of the world.",
        ot_text_kjv="Their line is gone out through all the earth, and their words to the end of the world.",
        ot_hebrew="בְּכָל־הָאָרֶץ יָצָא קַוָּם וּבִקְצֵה תֵבֵל מִלֵּיהֶם",
        lxx_reading="εἰς πᾶσαν τὴν γῆν ἐξῆλθεν ὁ φθόγγος αὐτῶν καὶ εἰς τὰ πέρατα τῆς οἰκουμένης τὰ ῥήματα αὐτῶν",
        covenant_theme="Universal Proclamation of God's Word",
        theological_significance="Applies the cosmic witness of creation in Psalm 19 typologically to the global herald of the apostolic gospel.",
    ),
    OTCitation(
        nt_osis="Rom.11.26",
        ot_osis="Isa.59.20",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 59:20–21 / Jer 31:33",
        nt_ref_display="Romans 11:26–27",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς γέγραπται (As it is written)",
        nt_text_snippet="There shall come out of Sion the Deliverer, and shall turn away ungodliness from Jacob: For this is my covenant unto them, when I shall take away their sins.",
        ot_text_kjv="And the Redeemer shall come to Zion, and unto them that turn from transgression in Jacob, saith the LORD. As for me, this is my covenant with them, saith the LORD...",
        ot_hebrew="וּבָא לְצִיּוֹן גּוֹאֵל וּלְשָׁבֵי פֶשַׁע בְּיַעֲקֹב נְאֻם־יְהוָה",
        lxx_reading="ἥξει ἐκ Σιὼν ὁ ῥυόμενος καὶ ἀποστρέψει ἀσεβείας ἀπὸ Ἰακώβ",
        covenant_theme="The Final Deliverance & New Covenant Remnant",
        theological_significance=(
            "The grand theological climax of Romans 9–11: God has not cast off His covenant people. In the final consummation, "
            "the Redeemer out of Zion will fulfill the covenant promises, turning ungodliness away and cleansing sin."
        ),
    ),
    OTCitation(
        nt_osis="Rom.12.19",
        ot_osis="Deut.32.35",
        ot_book="Deuteronomy",
        ot_ref_display="Deuteronomy 32:35",
        nt_ref_display="Romans 12:19",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="γέγραπται γάρ (For it is written)",
        nt_text_snippet="Vengeance is mine; I will repay, saith the Lord.",
        ot_text_kjv="To me belongeth vengeance, and recompence; their foot shall slide in due time...",
        ot_hebrew="לִי נָקָם וְשִׁלֵּם",
        lxx_reading="ἐν ἡμέρᾳ ἐκδικήσεως ἀνταποδώσω",
        covenant_theme="Divine Prerogative of Justice / Non-Retaliation",
        theological_significance=(
            "The ethical turning point of Romans 12: believers surrender personal retaliation and leave room for God's holy wrath, "
            "because supreme moral justice belongs exclusively to the sovereign Judge."
        ),
    ),
    OTCitation(
        nt_osis="Rom.12.20",
        ot_osis="Prov.25.21",
        ot_book="Proverbs",
        ot_ref_display="Proverbs 25:21–22",
        nt_ref_display="Romans 12:20",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἀλλὰ (Therefore)",
        nt_text_snippet="If thine enemy hunger, feed him; if he thirst, give him drink: for in so doing thou shalt heap coals of fire on his head.",
        ot_text_kjv="If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink: For thou shalt heap coals of fire upon his head, and the LORD shall reward thee.",
        ot_hebrew="אִם־רָעֵב שֹׂנַאֲךָ הַאֲכִלֵהוּ לָחֶם וְאִם־צָמֵא הַשְׁקֵהוּ מָיִם",
        lxx_reading="ἐὰν πεινᾷ ὁ ἐχθρός σου, ψώμιζε αὐτόν... ἄνθρακας γὰρ πυρὸς σωρεύσεις ἐπὶ τὴν κεφαλὴν αὐτοῦ",
        covenant_theme="Overcoming Evil with Selfless Love",
        theological_significance=(
            "Direct application of Solomon's wisdom: responding to enmity with tangible kindness acts like coals of fire, "
            "melting hostility and awakening conviction."
        ),
    ),

    # ── GALATIANS ──────────────────────────────────────────────────────────
    OTCitation(
        nt_osis="Gal.3.6",
        ot_osis="Gen.15.6",
        ot_book="Genesis",
        ot_ref_display="Genesis 15:6",
        nt_ref_display="Galatians 3:6",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς (Even as)",
        nt_text_snippet="Even as Abraham believed God, and it was accounted to him for righteousness.",
        ot_text_kjv="And he believed in the LORD; and he counted it to him for righteousness.",
        ot_hebrew="וְהֶאֱמִן בַּיהוָה וַיַּחְשְׁבֶהָ לּוֹ צְדָקָה",
        lxx_reading="καὶ ἐπίστευσεν Ἀβρὰμ τῷ θεῷ, καὶ ἐλογίσθη αὐτῷ εἰς δικαιοσύνην",
        covenant_theme="Righteousness by Faith Alone",
        theological_significance="Rebukes Galatian legalism by proving the patriarchal gospel preceded circumcision and works of law.",
    ),
    OTCitation(
        nt_osis="Gal.3.10",
        ot_osis="Deut.27.26",
        ot_book="Deuteronomy",
        ot_ref_display="Deuteronomy 27:26",
        nt_ref_display="Galatians 3:10",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="γέγραπται γὰρ ὅτι (For it is written)",
        nt_text_snippet="Cursed is every one that continueth not in all things which are written in the book of the law to do them.",
        ot_text_kjv="Cursed be he that confirmeth not all the words of this law to do them. And all the people shall say, Amen.",
        ot_hebrew="אָרוּר אֲשֶׁר לֹא־יָקִים אֶת־דִּבְרֵי הַתּוֹרָה־הַזֹּאת לַעֲשׂוֹת אוֹתָם",
        lxx_reading="ἐπικατάρατος πᾶς ἄνθρωπος ὃς οὐκ ἐμμένει ἐν πᾶσιν τοῖς λόγοις τοῦ νόμου τούτου",
        covenant_theme="The Absolute Demands of Legalism",
        theological_significance=(
            "Paul exposes the fatal trap of legalism: seeking righteousness by the law binds one to 100% continuous, "
            "unbroken perfection; a single infraction brings the full covenant curse."
        ),
    ),
    OTCitation(
        nt_osis="Gal.3.11",
        ot_osis="Hab.2.4",
        ot_book="Habakkuk",
        ot_ref_display="Habakkuk 2:4",
        nt_ref_display="Galatians 3:11",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ὅτι δὲ... δῆλον, ὅτι (That no man is justified... it is evident: for)",
        nt_text_snippet="The just shall live by faith.",
        ot_text_kjv="The just shall live by his faith.",
        ot_hebrew="וְצַדִּיק בֶּאֱמוּנָתוֹ יִחְיֶה",
        lxx_reading="ὁ δὲ δίκαιος ἐκ πίστεώς μου ζήσεται",
        covenant_theme="Faith as the Only Path of Life",
        theological_significance="Habakkuk 2:4 used to prove the categorical incompatibility between legal merit and the life of faith.",
    ),
    OTCitation(
        nt_osis="Gal.3.12",
        ot_osis="Lev.18.5",
        ot_book="Leviticus",
        ot_ref_display="Leviticus 18:5",
        nt_ref_display="Galatians 3:12",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἀλλ’ (But)",
        nt_text_snippet="The man that doeth them shall live in them.",
        ot_text_kjv="Which if a man do, he shall live in them: I am the LORD.",
        ot_hebrew="אֲשֶׁר יַעֲשֶׂה אֹתָם הָאָדָם וָחַי בָּהֶם",
        lxx_reading="ὁ ποιήσας αὐτὰ ζήσεται ἐν αὐτοῖς",
        covenant_theme="Law Operates on Performance, Not Faith",
        theological_significance="Demonstrates that the law's operational principle is based on performance ('doeth them'), contrasting sharply with faith.",
    ),
    OTCitation(
        nt_osis="Gal.3.13",
        ot_osis="Deut.21.23",
        ot_book="Deuteronomy",
        ot_ref_display="Deuteronomy 21:23",
        nt_ref_display="Galatians 3:13",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="γέγραπται γάρ (For it is written)",
        nt_text_snippet="Cursed is every one that hangeth on a tree.",
        ot_text_kjv="His body shall not remain all night upon the tree... for he that is hanged is accursed of God...",
        ot_hebrew="כִּי־קִלְלַת אֱלֹהִים תָּלוּי",
        lxx_reading="κεκατηραμένος ὑπὸ θεοῦ πᾶς κρεμάμενος ἐπὶ ξύλου",
        covenant_theme="Substitutionary Atonement on the Cross",
        theological_significance=(
            "The heart of Galatians: Christ redeemed us from the curse of the law by becoming a curse for us. "
            "By hanging on the cross, Jesus bore the judicial covenant penalty due to our transgression."
        ),
    ),
    OTCitation(
        nt_osis="Gal.3.16",
        ot_osis="Gen.22.18",
        ot_book="Genesis",
        ot_ref_display="Genesis 12:7 / Genesis 22:18",
        nt_ref_display="Galatians 3:16",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="οὐ λέγει... ἀλλ’ ὡς ἐφ’ ἑνός (He saith not... but as of one)",
        nt_text_snippet="And to thy seed, which is Christ.",
        ot_text_kjv="And in thy seed shall all the nations of the earth be blessed; because thou hast obeyed my voice.",
        ot_hebrew="וְהִתְבָּרֲכוּ בְזַרְעֲךָ כֹּל גּוֹיֵי הָאָרֶץ",
        lxx_reading="καὶ ἐνευλογηθήσονται ἐν τῷ σπέρματί σου πάντα τὰ ἔθνη τῆς γῆς",
        covenant_theme="Christ the Singular Seed of Abraham",
        theological_significance=(
            "Paul provides inspired grammatical exposition: the promise was made to Abraham and his 'Seed' (singular, zera / sperma), "
            "pointing directly to the Messiah, not plural ethnic descendants."
        ),
    ),
    OTCitation(
        nt_osis="Gal.4.27",
        ot_osis="Isa.54.1",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 54:1",
        nt_ref_display="Galatians 4:27",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="γέγραπται γάρ (For it is written)",
        nt_text_snippet="Rejoice, thou barren that bearest not; break forth and cry, thou that travailest not: for the desolate hath many more children than she which hath an husband.",
        ot_text_kjv="Sing, O barren, thou that didst not bear; break forth into singing... for more are the children of the desolate than the children of the married wife, saith the LORD.",
        ot_hebrew="רָנִּי עֲקָרָה לֹא יָלָדָה פִּצְחִי רִנָּה וְצַהֲלִי",
        lxx_reading="εὐφράνθητι στεῖρα ἡ οὐ τίκτουσα... ὅτι πολλὰ τὰ τέκνα τῆς ἐρήμου μᾶλλον ἢ τῆς ἐχούσης τὸν ἄνδρα",
        covenant_theme="Jerusalem Above / The Barren Fruitful",
        theological_significance=(
            "Typological application of Isaiah's post-exilic prophecy to Sarah (the New Covenant, Jerusalem above) "
            "whose spiritual offspring outnumber earthly Hagar (Sinai legalism)."
        ),
    ),
    OTCitation(
        nt_osis="Gal.4.30",
        ot_osis="Gen.21.10",
        ot_book="Genesis",
        ot_ref_display="Genesis 21:10",
        nt_ref_display="Galatians 4:30",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἀλλὰ τί λέγει ἡ γραφή; (Nevertheless what saith the scripture?)",
        nt_text_snippet="Cast out the bondwoman and her son: for the son of the bondwoman shall not be heir with the son of the freewoman.",
        ot_text_kjv="Wherefore she said unto Abraham, Cast out this bondwoman and her son: for the son of this bondwoman shall not be heir with my son, even with Isaac.",
        ot_hebrew="גָּרֵשׁ הָאָמָה הַזֹּאת וְאֶת־בְּנָהּ כִּי לֹא יִירַשׁ בֶּן־הָאָמָה הַזֹּאת עִם־בְּנִי עִם־יִצְחָק",
        lxx_reading="ἔκβαλε τὴν παιδίσκην ταύτην καὶ τὸν υἱὸν αὐτῆς",
        covenant_theme="Casting Out Works of the Flesh",
        theological_significance="Sarah's command is elevated to divine Scripture: legalism cannot co-exist with grace; works cannot share the inheritance with faith.",
    ),

    # ── EPHESIANS ──────────────────────────────────────────────────────────
    OTCitation(
        nt_osis="Eph.4.8",
        ot_osis="Ps.68.18",
        ot_book="Psalms",
        ot_ref_display="Psalm 68:18",
        nt_ref_display="Ephesians 4:8",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="διὸ λέγει (Wherefore he saith)",
        nt_text_snippet="When he ascended up on high, he led captivity captive, and gave gifts unto men.",
        ot_text_kjv="Thou hast ascended on high, thou hast led captivity captive: thou hast received gifts for men; yea, for the rebellious also, that the LORD God might dwell among them.",
        ot_hebrew="עָלִיתָ לַמָּרוֹם שָׁבִיתָ שֶּׁבִי לָקַחְתָּ מַתָּנוֹת בָּאָדָם",
        lxx_reading="ἀνέβης εἰς ὕψος, ᾐχμαλώτευσας αἰχμαλωσίαν, ἔλαβες δόματα ἐν ἀνθρώπῳ",
        covenant_theme="The Ascended King & Spiritual Gifts",
        theological_significance=(
            "Paul interprets Psalm 68 as Christ's triumphant ascension back to the Father's throne after conquering sin and death, "
            "where He received and poured out the Holy Spirit and spiritual gifts upon His body, the church."
        ),
    ),
    OTCitation(
        nt_osis="Eph.5.31",
        ot_osis="Gen.2.24",
        ot_book="Genesis",
        ot_ref_display="Genesis 2:24",
        nt_ref_display="Ephesians 5:31–32",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἀντὶ τούτου (For this cause)",
        nt_text_snippet="For this cause shall a man leave his father and mother, and shall be joined unto his wife, and they two shall be one flesh. This is a great mystery: but I speak concerning Christ and the church.",
        ot_text_kjv="Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh.",
        ot_hebrew="עַל־כֵּן יַעֲזָב־אִישׁ אֶת־אָבִיו וְאֶת־אִמּוֹ וְדָבַק בְּאִשְׁתּוֹ וְהָיוּ לְבָשָׂר אֶחָד",
        lxx_reading="ἕνεκεν τούτου καταλείψει ἄνθρωπος τὸν πατέρα αὐτοῦ καὶ τὴν μητέρα... καὶ ἔσονται οἱ δύο εἰς σάρκα μίαν",
        covenant_theme="Eden Marriage Typology of Christ and Church",
        theological_significance=(
            "The Edenic institution of marriage in Genesis 2:24 is unveiled as a profound prophetic mystery pointing directly "
            "to the indivisible, self-sacrificing union between Christ and His redeemed bride."
        ),
    ),
    OTCitation(
        nt_osis="Eph.6.2",
        ot_osis="Exod.20.12",
        ot_book="Exodus",
        ot_ref_display="Exodus 20:12 / Deut 5:16",
        nt_ref_display="Ephesians 6:2–3",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἥτις ἐστὶν ἐντολὴ πρώτη ἐν ἐπαγγελίᾳ (Which is the first commandment with promise)",
        nt_text_snippet="Honour thy father and mother... That it may be well with thee, and thou mayest live long on the earth.",
        ot_text_kjv="Honour thy father and thy mother: that thy days may be long upon the land which the LORD thy God giveth thee.",
        ot_hebrew="כַּבֵּד אֶת־אָבִיךָ וְאֶת־אִמֶּךָ לְמַעַן יַאֲרִכוּן יָמֶיךָ",
        lxx_reading="τίμα τὸν πατέρα σου καὶ τὴν μητέρα σου... ἵνα εὖ σοι γένηται",
        covenant_theme="The Fifth Commandment in the New Covenant",
        theological_significance="Proves the enduring moral validity of the Ten Commandments in apostolic New Testament ethics.",
    ),

    # ── HEBREWS ────────────────────────────────────────────────────────────
    OTCitation(
        nt_osis="Heb.1.5",
        ot_osis="Ps.2.7",
        ot_book="Psalms",
        ot_ref_display="Psalm 2:7 / 2 Sam 7:14",
        nt_ref_display="Hebrews 1:5",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="τίνι γὰρ εἶπέν ποτε τῶν ἀγγέλων (For unto which of the angels said he at any time)",
        nt_text_snippet="Thou art my Son, this day have I begotten thee? And again, I will be to him a Father, and he shall be to me a Son?",
        ot_text_kjv="The LORD hath said unto me, Thou art my Son; this day have I begotten thee. / I will be his father, and he shall be my son.",
        ot_hebrew="יְהוָה אָמַר אֵלַי בְּנִי אַתָּה אֲנִי הַיּוֹם יְלִדְתִּיךָ / אֲנִי אֶהְיֶה־לּוֹ לְאָב וְהוּא יִהְיֶה־לִּי לְבֵן",
        lxx_reading="υἱός μου εἶ σύ, ἐγὼ σήμερον γεγέννηκά σε",
        covenant_theme="Royal Messiahship / Divine Sonship",
        theological_significance=(
            "Establishes Christ's infinite superiority over created angels: Christ is the eternal Son and Davidic King "
            "covenanted in 2 Samuel 7 and Psalm 2."
        ),
    ),
    OTCitation(
        nt_osis="Heb.1.8",
        ot_osis="Ps.45.6",
        ot_book="Psalms",
        ot_ref_display="Psalm 45:6–7",
        nt_ref_display="Hebrews 1:8–9",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="πρὸς δὲ τὸν υἱόν (But unto the Son he saith)",
        nt_text_snippet="Thy throne, O God, is for ever and ever: a sceptre of righteousness is the sceptre of thy kingdom.",
        ot_text_kjv="Thy throne, O God, is for ever and ever: the sceptre of thy kingdom is a right sceptre. Thou lovest righteousness, and hatest wickedness: therefore God, thy God, hath anointed thee...",
        ot_hebrew="כִּסְאֲךָ אֱלֹהִים עוֹלָם וָעֶד שֵׁבֶט מִישֹׁר שֵׁבֶט מַלְכוּתֶךָ",
        lxx_reading="ὁ θρόνος σου, ὁ θεός, εἰς τὸν αἰῶνα τοῦ αἰῶνος",
        covenant_theme="Direct Deity of the Son",
        theological_significance=(
            "The Father addresses the Son directly as God ('Elohim' / 'ho Theos'), possessing an eternal throne "
            "founded upon absolute righteousness."
        ),
    ),
    OTCitation(
        nt_osis="Heb.1.10",
        ot_osis="Ps.102.25",
        ot_book="Psalms",
        ot_ref_display="Psalm 102:25–27",
        nt_ref_display="Hebrews 1:10–12",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καί (And)",
        nt_text_snippet="Thou, Lord, in the beginning hast laid the foundation of the earth; and the heavens are the works of thine hands: They shall perish; but thou remainest...",
        ot_text_kjv="Of old hast thou laid the foundation of the earth: and the heavens are the work of thy hands. They shall perish, but thou shalt endure...",
        ot_hebrew="לְפָנִים הָאָרֶץ יָסַדְתָּ וּמַעֲשֵׂה יָדֶיךָ שָׁמָיִם",
        lxx_reading="σὺ κατ’ ἀρχάς, κύριε, τὴν γῆν ἐθεμελίωσας",
        covenant_theme="The Son as Unchanging Creator",
        theological_significance=(
            "Applies Psalm 102's praise of Yahweh the Creator directly to Jesus Christ: creation grows old like a garment, "
            "but Christ remains eternally the same."
        ),
    ),
    OTCitation(
        nt_osis="Heb.1.13",
        ot_osis="Ps.110.1",
        ot_book="Psalms",
        ot_ref_display="Psalm 110:1",
        nt_ref_display="Hebrews 1:13",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="πρὸς τίνα δὲ τῶν ἀγγέλων εἴρηκέν ποτε (But to which of the angels said he at any time)",
        nt_text_snippet="Sit on my right hand, until I make thine enemies thy footstool?",
        ot_text_kjv="The LORD said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.",
        ot_hebrew="נְאֻם יְהוָה לַאדֹנִי שֵׁב לִימִינִי עַד־אָשִׁית אֹיְבֶיךָ הֲדֹם לְרַגְלֶיךָ",
        lxx_reading="κάθου ἐκ δεξιῶν μου, ἕως ἂν θῶ τοὺς ἐχθρούς σου ὑποπόδιον τῶν ποδῶν σου",
        covenant_theme="Session at God's Right Hand",
        theological_significance="The most quoted OT verse in the NT, establishing Christ's exalted heavenly session until the total subjugation of all evil.",
    ),
    OTCitation(
        nt_osis="Heb.2.6",
        ot_osis="Ps.8.4",
        ot_book="Psalms",
        ot_ref_display="Psalm 8:4–6",
        nt_ref_display="Hebrews 2:6–8",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="διεμαρτύρατο δέ πού τις λέγων (But one in a certain place testified, saying)",
        nt_text_snippet="What is man, that thou art mindful of him? or the son of man, that thou visitest him? Thou madest him a little lower than the angels; thou crownedst him with glory and honour...",
        ot_text_kjv="What is man, that thou art mindful of him? and the son of man, that thou visitest him? For thou hast made him a little lower than the angels, and hast crowned him with glory and honour.",
        ot_hebrew="מָה־אֱנוֹשׁ כִּי־תִזְכְּרֶנּוּ וּבֶן־אָדָם כִּי תִפְקְדֶנּוּ",
        lxx_reading="τί ἐστιν ἄνθρωπος ὅτι μιμνῄσκῃ αὐτοῦ; ... ἠλάττωσας αὐτὸν βραχύ τι παρ’ ἀγγέλους",
        covenant_theme="Incarnation & Recovered Dominion",
        theological_significance=(
            "David's meditation on Adam's lost dominion is fulfilled in Jesus, who was made lower than angels for the suffering of death, "
            "now crowned with glory and honor to bring many sons unto glory."
        ),
    ),
    OTCitation(
        nt_osis="Heb.3.7",
        ot_osis="Ps.95.7",
        ot_book="Psalms",
        ot_ref_display="Psalm 95:7–11",
        nt_ref_display="Hebrews 3:7–11",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς λέγει τὸ πνεῦμα τὸ ἅγιον (Wherefore as the Holy Ghost saith)",
        nt_text_snippet="To day if ye will hear his voice, Harden not your hearts, as in the provocation, in the day of temptation in the wilderness...",
        ot_text_kjv="To day if ye will hear his voice, Harden not your heart, as in the provocation, and as in the day of temptation in the wilderness...",
        ot_hebrew="הַיּוֹם אִם־בְּקֹלוֹ תִשְׁמָעוּ אַל־תַּקְשׁוּ לְבַבְכֶם כִּמְרִיבָה",
        lxx_reading="σήμερον ἐὰν τῆς φωνῆς αὐτοῦ ἀκούσητε, μὴ σκληρύνητε τὰς καρδίας ὑμῶν",
        covenant_theme="Warning Against Wilderness Unbelief",
        theological_significance=(
            "Attributed explicitly to the Holy Spirit speaking in the present ('To day'). Warns the church against the fatal unbelief "
            "that barred ancient Israel from entering God's covenant rest."
        ),
    ),
    OTCitation(
        nt_osis="Heb.4.4",
        ot_osis="Gen.2.2",
        ot_book="Genesis",
        ot_ref_display="Genesis 2:2",
        nt_ref_display="Hebrews 4:4",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="εἴρηκεν γάρ που... οὕτως (For he spake in a certain place on this wise)",
        nt_text_snippet="And God did rest the seventh day from all his works.",
        ot_text_kjv="And on the seventh day God ended his work which he had made; and he rested on the seventh day from all his work which he had made.",
        ot_hebrew="וַיִּשְׁבֹּת בַּיּוֹם הַשְּׁבִיעִי מִכָּל־מְלַאכְתּוֹ אֲשֶׁר עָשָׂה",
        lxx_reading="καὶ κατέπαυσεν ὁ θεὸς ἐν τῇ ἡμέρᾳ τῇ ἑβδόμῃ ἀπὸ πάντων τῶν ἔργων αὐτοῦ",
        covenant_theme="Creation Sabbath & Redemptive Sabbatismos",
        theological_significance=(
            "The Creation Seventh-Day Sabbath is the divine archetype of rest. As God rested when His creation was finished, "
            "so the believer ceases from his own self-justifying works to rest in Christ's completed redemption (Heb 4:9-10)."
        ),
    ),
    OTCitation(
        nt_osis="Heb.5.6",
        ot_osis="Ps.110.4",
        ot_book="Psalms",
        ot_ref_display="Psalm 110:4",
        nt_ref_display="Hebrews 5:6 / Heb 7:17, 21",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="καθὼς καὶ ἐν ἑτέρῳ λέγει (As he saith also in another place)",
        nt_text_snippet="Thou art a priest for ever after the order of Melchisedec.",
        ot_text_kjv="The LORD hath sworn, and will not repent, Thou art a priest for ever after the order of Melchizedek.",
        ot_hebrew="נִשְׁבַּע יְהוָה וְלֹא יִנָּחֵם אַתָּה־כֹהֵן לְעוֹלָם עַל־דִּבְרָתִי מַלְכִּי־צֶדֶק",
        lxx_reading="σὺ ἱερεὺς εἰς τὸν αἰῶνα κατὰ τὴν τάξιν Μελχισεδέκ",
        covenant_theme="Eternal High Priesthood of Melchizedek",
        theological_significance=(
            "The bedrock of Hebrews' sanctuary theology: Jesus' priesthood is not Aaronic (which was mortal and temporary), "
            "but confirmed with God's inviolable oath according to the indestructible life of Melchizedek—King of Righteousness and Peace."
        ),
    ),
    OTCitation(
        nt_osis="Heb.8.8",
        ot_osis="Jer.31.31",
        ot_book="Jeremiah",
        ot_ref_display="Jeremiah 31:31–34",
        nt_ref_display="Hebrews 8:8–12 / Heb 10:16–17",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="μεμφόμενος γὰρ αὐτοὺς λέγει (For finding fault with them, he saith)",
        nt_text_snippet="Behold, the days come, saith the Lord, when I will make a new covenant with the house of Israel... I will put my laws into their mind, and write them in their hearts: and I will be to them a God, and they shall be to me a people...",
        ot_text_kjv="Behold, the days come, saith the LORD, that I will make a new covenant with the house of Israel... I will put my law in their inward parts, and write it in their hearts; and will be their God, and they shall be my people.",
        ot_hebrew="הִנֵּה יָמִים בָּאִים נְאֻם־יְהוָה וְכָרַתִּי... בְּרִית חֲדָשָׁה... נָתַתִּי אֶת־תּוֹרָתִי בְּקִרְבָּם וְעַל־לִבָּם אֶכְתֲּבֶנָּה",
        lxx_reading="ἰδοὺ ἡμέραι ἔρχονται, λέγει κύριος, καὶ συντελέσω... διαθήκην καινήν",
        covenant_theme="The New Covenant Heart Inscription",
        theological_significance=(
            "The longest OT citation in the New Testament. The fault with the first covenant was with the people's fickle promises ('them'); "
            "the New Covenant transfers the Torah from cold tables of stone to warm human hearts via the Holy Spirit, backed by divine promises."
        ),
    ),
    OTCitation(
        nt_osis="Heb.9.20",
        ot_osis="Exod.24.8",
        ot_book="Exodus",
        ot_ref_display="Exodus 24:8",
        nt_ref_display="Hebrews 9:20",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="λέγων (Saying)",
        nt_text_snippet="This is the blood of the testament which God hath enjoined unto you.",
        ot_text_kjv="And Moses took the blood, and sprinkled it on the people, and said, Behold the blood of the covenant, which the LORD hath made with you concerning all these words.",
        ot_hebrew="וַיִּקַּח מֹשֶׁה אֶת־הַדָּם וַיִּזְרֹק עַל־הָעָם וַיֹּאמֶר הִנֵּה דַם־הַבְּרִית",
        lxx_reading="τοῦτο τὸ αἷμα τῆς διαθήκης ἧς ἐνετείλατο πρὸς ὑμᾶς ὁ θεός",
        covenant_theme="Covenant Inauguration by Blood",
        theological_significance=(
            "Reminds the reader that neither the Old nor the New Covenant was inaugurated without blood. Moses' sprinkling at Sinai "
            "pointed forward to Christ sprinkling His own blood in the heavenly sanctuary."
        ),
    ),
    OTCitation(
        nt_osis="Heb.10.5",
        ot_osis="Ps.40.6",
        ot_book="Psalms",
        ot_ref_display="Psalm 40:6–8",
        nt_ref_display="Hebrews 10:5–7",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="διὸ εἰσερχόμενος εἰς τὸν κόσμον λέγει (Wherefore when he cometh into the world, he saith)",
        nt_text_snippet="Sacrifice and offering thou wouldest not, but a body hast thou prepared me: In burnt offerings and sacrifices for sin thou hast had no pleasure. Then said I, Lo, I come... to do thy will, O God.",
        ot_text_kjv="Sacrifice and offering thou didst not desire; mine ears hast thou opened: burnt offering and sin offering hast thou not required. Then said I, Lo, I come: in the volume of the book it is written of me, I delight to do thy will, O my God...",
        ot_hebrew="זֶבַח וּמִנְחָה לֹא־חָפַצְתָּ אָזְנַיִם כָּרִיתָ לִּי... אָז אָמַרְתִּי הִנֵּה־בָאתִי... לַעֲשׂוֹת־רְצוֹנְךָ אֱלֹהַי חָפָצְתִּי",
        lxx_reading="θυσίαν καὶ προσφορὰν οὐκ ἠθέλησας, σῶμα δὲ κατηρτίσω μοι",
        covenant_theme="Incarnate Obedience Replaces Shadows",
        theological_significance=(
            "Follows the Septuagint ('a body hast thou prepared me'). Animal sacrifices could never take away sins; "
            "Christ took human flesh to offer the one, perfect, living sacrifice of obedience once for all."
        ),
    ),
    OTCitation(
        nt_osis="Heb.10.38",
        ot_osis="Hab.2.4",
        ot_book="Habakkuk",
        ot_ref_display="Habakkuk 2:3–4",
        nt_ref_display="Hebrews 10:37–38",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="[Eschatological Encouragement]",
        nt_text_snippet="Now the just shall live by faith: but if any man draw back, my soul shall have no pleasure in him.",
        ot_text_kjv="For the vision is yet for an appointed time... though it tarry, wait for it; because it will surely come... but the just shall live by his faith.",
        ot_hebrew="וְצַדִּיק בֶּאֱמוּנָתוֹ יִחְיֶה",
        lxx_reading="ὁ δὲ δίκαιός μου ἐκ πίστεως ζήσεται· καὶ ἐὰν ὑποστείληται, οὐκ εὐδοκεῖ ἡ ψυχή μου ἐν αὐτῷ",
        covenant_theme="Endurance in Hope Until the Advent",
        theological_significance=(
            "The third great NT citation of Habakkuk 2:4 (alongside Rom 1:17 and Gal 3:11). Here the emphasis is eschatological endurance: "
            "while waiting for the Coming One, the righteous must never shrink back to perdition, but preserve the soul through faith."
        ),
    ),
    OTCitation(
        nt_osis="Heb.12.5",
        ot_osis="Prov.3.11",
        ot_book="Proverbs",
        ot_ref_display="Proverbs 3:11–12",
        nt_ref_display="Hebrews 12:5–6",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἥτις ὑμῖν ὡς υἱοῖς διαλέγεται (Which speaketh unto you as unto children)",
        nt_text_snippet="My son, despise not thou the chastening of the Lord, nor faint when thou art rebuked of him: For whom the Lord loveth he chasteneth, and scourgeth every son whom he receiveth.",
        ot_text_kjv="My son, despise not the chastening of the LORD; neither be weary of his correction: For whom the LORD loveth he correcteth; even as a father the son in whom he delighteth.",
        ot_hebrew="מוּסַר יְהוָה בְּנִי אַל־תִּמְאָס וְאַל־תָּקֹץ בְּתוֹכַחְתּוֹ כִּי אֶת אֲשֶׁר יֶאֱהַב יְהוָה יוֹכִיחַ",
        lxx_reading="υἱέ μου, μὴ ὀλιγώρει παιδείας Κυρίου... ὃν γὰρ ἀγαπᾷ Κύριος παιδεύει",
        covenant_theme="Covenant Discipline / Fatherly Love",
        theological_significance="Interprets affliction and trial not as divine rejection, but as positive proof of genuine covenant sonship.",
    ),
    OTCitation(
        nt_osis="Heb.13.5",
        ot_osis="Josh.1.5",
        ot_book="Joshua",
        ot_ref_display="Joshua 1:5 / Deut 31:6, 8",
        nt_ref_display="Hebrews 13:5",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="αὐτὸς γὰρ εἴρηκεν (For he hath said)",
        nt_text_snippet="I will never leave thee, nor forsake thee.",
        ot_text_kjv="There shall not any man be able to stand before thee all the days of thy life... I will not fail thee, nor forsake thee.",
        ot_hebrew="לֹא אַרְפְּךָ וְלֹא אֶעֶזְבֶךָּ",
        lxx_reading="οὐκ ἀνήσω σε οὐδ’ οὐ μὴ ἐγκαταλίπω σε",
        covenant_theme="Unconditional Divine Presence",
        theological_significance=(
            "The promise made to Joshua before crossing the Jordan is given to every believer to banish anxiety and greed: "
            "God's personal presence is our perpetual security."
        ),
    ),

    # ── 1 & 2 PETER ────────────────────────────────────────────────────────
    OTCitation(
        nt_osis="1Pet.1.16",
        ot_osis="Lev.11.44",
        ot_book="Leviticus",
        ot_ref_display="Leviticus 11:44 / Lev 19:2",
        nt_ref_display="1 Peter 1:16",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="διότι γέγραπται (Because it is written)",
        nt_text_snippet="Be ye holy; for I am holy.",
        ot_text_kjv="For I am the LORD your God: ye shall therefore sanctify yourselves, and ye shall be holy; for I am holy...",
        ot_hebrew="וְהִתְקַדִּשְׁתֶּם וִהְיִיתֶם קְדֹשִׁים כִּי קָדוֹשׁ אָנִי",
        lxx_reading="ἅγιοι ἔσεσθε, ὅτι ἐγὼ ἅγιός εἰμι",
        covenant_theme="The Call to Covenant Holiness",
        theological_significance=(
            "Peter grounds the ethical call of New Covenant believers directly in the Sanctuary holiness code of Leviticus: "
            "as blood-bought children of the Father, our character must reflect His holiness."
        ),
    ),
    OTCitation(
        nt_osis="1Pet.1.24",
        ot_osis="Isa.40.6",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 40:6–8",
        nt_ref_display="1 Peter 1:24–25",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="διότι (For)",
        nt_text_snippet="For all flesh is as grass, and all the glory of man as the flower of grass. The grass withereth, and the flower thereof falleth away: But the word of the Lord endureth for ever.",
        ot_text_kjv="All flesh is grass, and all the goodliness thereof is as the flower of the field: The grass withereth, the flower fadeth... but the word of our God shall stand for ever.",
        ot_hebrew="כָּל־הַבָּשָׂר חָצִיר וְכָל־חַסְדּוֹ כְּצִיץ הַשָּׂדֶה... וּדְבַר־אֱלֹהֵינוּ יָקוּם לְעוֹלָם",
        lxx_reading="πᾶσα σὰρξ ὡς χόρτος... τὸ δὲ ῥῆμα Κυρίου μένει εἰς τὸν αἰῶνα",
        covenant_theme="The Imperishable Word of God",
        theological_significance=(
            "Contrasts mortal, frail human transience with the eternal, incorruptible living Word through which believers "
            "are born again."
        ),
    ),
    OTCitation(
        nt_osis="1Pet.2.6",
        ot_osis="Isa.28.16",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 28:16",
        nt_ref_display="1 Peter 2:6",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="διότι περιέχει ἐν γραφῇ (Wherefore also it is contained in the scripture)",
        nt_text_snippet="Behold, I lay in Sion a chief corner stone, elect, precious: and he that believeth on him shall not be confounded.",
        ot_text_kjv="Behold, I lay in Zion for a foundation a stone, a tried stone, a precious corner stone, a sure foundation: he that believeth shall not make haste.",
        ot_hebrew="הִנְנִי יִסַּד בְּצִיּוֹן אָבֶן אֶבֶן בֹּחַן פִּנַּת יִקְרַת מוּסָד מוּסָד",
        lxx_reading="ἰδοὺ τίθημι ἐν Σιὼν λίθον ἀκρογωνιαῖον ἐκλεκτὸν ἔντιμον",
        covenant_theme="Christ the Chosen Foundation",
        theological_significance="Christ is the precious living cornerstone upon whom believers are built up as a spiritual temple.",
    ),
    OTCitation(
        nt_osis="1Pet.2.7",
        ot_osis="Ps.118.22",
        ot_book="Psalms",
        ot_ref_display="Psalm 118:22",
        nt_ref_display="1 Peter 2:7",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ἀπειθοῦσιν δέ (Unto them which be disobedient)",
        nt_text_snippet="The stone which the builders disallowed, the same is made the head of the corner.",
        ot_text_kjv="The stone which the builders refused is become the head stone of the corner.",
        ot_hebrew="אֶבֶן מָאֲסוּ הַבּוֹנִים הָיְתָה לְרֹאשׁ פִּנָּה",
        lxx_reading="λίθος ὃν ἀπεδοκίμασαν οἱ οἰκοδομοῦντες, οὗτος ἐγενήθη εἰς κεφαλὴν γωνίας",
        covenant_theme="The Rejected Stone Exalted",
        theological_significance="Israel's human religious builders rejected the Messiah, but God made Him the supreme cornerstone.",
    ),
    OTCitation(
        nt_osis="1Pet.2.9",
        ot_osis="Exod.19.6",
        ot_book="Exodus",
        ot_ref_display="Exodus 19:5–6 / Isaiah 43:20–21",
        nt_ref_display="1 Peter 2:9",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ὑμεῖς δὲ (But ye are)",
        nt_text_snippet="But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people; that ye should shew forth the praises of him who hath called you out of darkness into his marvellous light.",
        ot_text_kjv="And ye shall be unto me a kingdom of priests, and an holy nation... / This people have I formed for myself; they shall shew forth my praise.",
        ot_hebrew="וְאַתֶּם תִּהְיוּ־לִי מַמְלֶכֶת כֹּהֲנִים וְגוֹי קָדוֹשׁ",
        lxx_reading="βασίλειον ἱεράτευμα καὶ ἔθνος ἅγιον",
        covenant_theme="Royal Priesthood of All Believers",
        theological_significance=(
            "The Sinai covenant titles of Israel are applied in their fullest spiritual reality to the New Covenant church: "
            "a royal priesthood consecrated to offer spiritual sacrifices and proclaim God's praises."
        ),
    ),
    OTCitation(
        nt_osis="1Pet.2.22",
        ot_osis="Isa.53.9",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 53:9",
        nt_ref_display="1 Peter 2:22",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="ὃς (Who)",
        nt_text_snippet="Who did no sin, neither was guile found in his mouth.",
        ot_text_kjv="And he made his grave with the wicked, and with the rich in his death; because he had done no violence, neither was any deceit in his mouth.",
        ot_hebrew="עַל לֹא־חָמָס עָשָׂה וְלֹא מִרְמָה בְּפִיו",
        lxx_reading="ὃς ἁμαρτίαν οὐκ ἐποίησεν οὐδὲ εὑρέθη δόλος ἐν τῷ στόματι αὐτοῦ",
        covenant_theme="The Sinless Suffering Servant",
        theological_significance="Presents Christ's spotless perfection under unjust suffering as both our vicarious atonement and our divine pattern.",
    ),
    OTCitation(
        nt_osis="1Pet.2.24",
        ot_osis="Isa.53.5",
        ot_book="Isaiah",
        ot_ref_display="Isaiah 53:5, 12",
        nt_ref_display="1 Peter 2:24",
        citation_type=CitationType.DIRECT_QUOTE,
        introductory_formula="οὗ τῷ μώλωπι (By whose stripes)",
        nt_text_snippet="Who his own self bare our sins in his own body on the tree... by whose stripes ye were healed.",
        ot_text_kjv="But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed.",
        ot_hebrew="וּבַחֲבֻרָתוֹ נִרְפָּא־לָנוּ",
        lxx_reading="οὗ τῷ μώλωπι ἰάθητε",
        covenant_theme="Healing through Substitutionary Wounds",
        theological_significance=(
            "The heart of Isaiah 53: Jesus bore our individual sins upon the cross so that we, being dead to sins, "
            "should live unto righteousness."
        ),
    ),
]


# ---------------------------------------------------------------------------
# Indexes for Sub-Millisecond Bidirectional Lookups
# ---------------------------------------------------------------------------

_NT_INDEX: dict[str, list[OTCitation]] = {}
_OT_INDEX: dict[str, list[OTCitation]] = {}

for _cit in _CANONICAL_CITATIONS:
    # 1. NT OSIS Index
    if _cit.nt_osis not in _NT_INDEX:
        _NT_INDEX[_cit.nt_osis] = []
    _NT_INDEX[_cit.nt_osis].append(_cit)

    # 2. OT OSIS Index
    if _cit.ot_osis not in _OT_INDEX:
        _OT_INDEX[_cit.ot_osis] = []
    _OT_INDEX[_cit.ot_osis].append(_cit)


def lookup_ot_citations_for_nt_verse(nt_osis: str) -> list[OTCitation]:
    """Return all Old Testament citations present in a given New Testament verse (e.g. 'Rom.1.17')."""
    return _NT_INDEX.get(nt_osis, [])


def lookup_nt_citations_for_ot_verse(ot_osis: str) -> list[OTCitation]:
    """Return all New Testament passages citing or anchoring to a given Old Testament verse (e.g. 'Hab.2.4')."""
    return _OT_INDEX.get(ot_osis, [])


def lookup_citations_for_verse(osis_ref: str) -> list[OTCitation]:
    """Bidirectional lookup: returns citations whether the verse is New Testament or Old Testament."""
    if not osis_ref:
        return []
    # Check NT first
    nt_hits = _NT_INDEX.get(osis_ref)
    if nt_hits:
        return nt_hits
    # Check OT
    return _OT_INDEX.get(osis_ref, [])


def get_passage_ot_citations_batch(book: str, chapter: int) -> dict[str, list[OTCitation]]:
    """Batch-fetch all OT citations or NT anchors across an entire chapter in a single pass."""
    batch: dict[str, list[OTCitation]] = {}
    prefix = f"{book}.{chapter}."

    for osis, cits in _NT_INDEX.items():
        if osis.startswith(prefix):
            batch[osis] = list(cits)

    for osis, cits in _OT_INDEX.items():
        if osis.startswith(prefix):
            if osis in batch:
                batch[osis].extend(cits)
            else:
                batch[osis] = list(cits)

    return batch


def format_citation_badge(citation: OTCitation, for_verse_osis: str) -> str:
    """Format a compact, color-coded badge for verse headers in the Reader pane."""
    v_book = for_verse_osis.split(".")[0] if "." in for_verse_osis else for_verse_osis
    nt_book = citation.nt_osis.split(".")[0]
    is_nt = (v_book == nt_book)
    if is_nt:
        return f"[bold green]⟨OT Anchor: {escape(citation.ot_ref_display)}⟩[/bold green]"
    else:
        return f"[bold cyan]⟨Cited in NT: {escape(citation.nt_ref_display)}⟩[/bold cyan]"


def render_citation_card(citation: OTCitation, for_verse_osis: str = "") -> str:
    """Render an in-depth theological card for the workstation inspector."""
    lines: list[str] = []
    v_book = for_verse_osis.split(".")[0] if "." in for_verse_osis else ""
    is_ot = bool(v_book and v_book == citation.ot_osis.split(".")[0])
    header = "CITED IN NEW TESTAMENT" if is_ot else "OT CITATION ANCHOR"
    lines.append(f"[bold green]═══ SCRIPTURE INTERPRETING SCRIPTURE: {header} ═══[/bold green]")
    lines.append(f"[bold yellow]New Testament Reference:[/bold yellow] [bold white]{escape(citation.nt_ref_display)}[/bold white]")
    lines.append(f"[bold yellow]Old Testament Source:[/bold yellow]    [bold cyan]{escape(citation.ot_ref_display)}[/bold cyan] [dim]({citation.citation_type.value})[/dim]")
    lines.append(f"[bold yellow]Apostolic Formula:[/bold yellow]      [italic green]{escape(citation.introductory_formula)}[/italic green]")
    lines.append(f"[bold yellow]Covenant Theme:[/bold yellow]         [bold magenta]{escape(citation.covenant_theme)}[/bold magenta]\n")

    lines.append("[bold underline]Textual Comparison:[/bold underline]")
    lines.append(f"  [bold]NT Apostolic Text:[/bold] [italic]\"{escape(citation.nt_text_snippet)}\"[/italic]")
    lines.append(f"  [bold]OT Hebrew Source:[/bold]  [italic]\"{escape(citation.ot_text_kjv)}\"[/italic]")
    if citation.ot_hebrew:
        lines.append(f"    [dim]WLC Hebrew:[/dim] [bold green]{escape(citation.ot_hebrew)}[/bold green]")
    if citation.lxx_reading:
        lines.append(f"    [dim]Septuagint (LXX):[/dim] [cyan]{escape(citation.lxx_reading)}[/cyan]")
    lines.append("")

    lines.append("[bold underline]Apostolic Hermeneutic & Covenant Theology:[/bold underline]")
    lines.append(f"  {escape(citation.theological_significance)}")
    lines.append("")
    return "\n".join(lines)
